# Example Codem Config
#
# This config sets up:
# 1. A Rust project with test command
# 2. A Python project with custom test dir
# 3. Safe and risky command patterns

[[projects]]
name = "rust-project"
base_path = "/path/to/rust/project"
allowed_paths = [
    "/path/to/rust/project/tests",
    "/path/to/rust/project/benches"
]
test_command = "cargo test"

[[projects]]
name = "python-project"
base_path = "/path/to/python/project"
allowed_paths = ["/path/to/python/project/tests"]
test_command = "python -m pytest"

# Path where session data will be stored
# Parent directory must exist
session_file = "/path/to/sessions/sessions.toml"

# Safe commands don't need extra confirmation
# (unless they also match a risky pattern)
safe_patterns = [
    # Basic shell commands
    "^ls( -[a-zA-Z]+)?$",               # ls with optional flags
    "^pwd$",                            # Show current dir
    "^echo [a-zA-Z0-9_-]+$",           # Basic echo
    
    # Development commands
    "^cargo (test|check|fmt)$",         # Safe Rust commands  
    "^pytest( .*)?$",                   # Python tests
    "^grep -r \".*\" [a-zA-Z0-9/_-]+$", # Recursive grep
    "^git (status|log|diff)$"           # Safe git commands
]

# Risky commands need confirmation
risky_patterns = [
    # Destructive operations
    "^rm .*",                           # Any rm command
    "^git clean .*",                    # Git clean
    
    # Remote operations
    "^git (push|pull|fetch)",           # Git remote commands
    "^cargo publish",                   # Publishing to crates.io

    # Database operations  
    "^psql .*",                         # PostgreSQL access
    "^diesel .*"                        # Database migrations
]