[package]
name = "codem-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
wait-timeout = "0.2"
regex = "1.0"
anyhow = "1.0"
glob = "0.3.2"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.8"
